// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Learning example Users API
Prototpe API for test purposes


    Schemes:
      http
    Host: localhost:9000
    BasePath: /v1
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
